### ISSUE TITLE
How to get default filename  

### ISSUE THREAD

**Issue by PingguSoft** [quillford/OctoUpload#3]
Hi,

Thanks for your good work.
Actually I find how to get filename from loaded STL file and I want to share my findings.

import mimetools
import sys
+import os
<snip>
#remove extension user may have used on the filename
-outputName = outputName.split(".")[0]
+outputName = os.path.basename(profile.getPreference('lastFile'))
print outputName

I think this automatic file name generation will be more helpful.

Thanks.

**Comment by quillford** [comment]
Didn't know Cura gave plugins the path. Will implement that this week. Thanks!

**Comment by quillford** [comment]
Seems there is an error with profile.
```
NameError: 'name 'profile' is not defined' @ OctoUpload.py:<module>:50
```

**Comment by PingguSoft** [comment]
Add 'from Cura.util import profile" below import clause

I see gcode with stl file name is uploaded automatically with my changes.
And I tried to show notification message whether it is successful or not
but I didn't find the solution.
Do you have an idea about it?

Thanks.

**Comment by quillford** [comment]
So I now get a filename, but it is the wrong file reference.

**Comment by PingguSoft** [comment]
I also see wrong file reference only if the stl file is opened with "file
double click in explorer"
file reference is normal if you open stl file in Cura.

2015-05-07 14:37 GMT+09:00 quillford <notifications@github.com>:

**Comment by quillford** [comment]
I dragged it in.
