### ISSUE TITLE
Cant send to Octoprint

### ISSUE THREAD

**Issue by goblingift** [quillford/OctoUpload#5]
Hi,

i´m only getting a message "Failed to save", if i try to send the model to octoprint...
I´ve entered the API key and the IP adress, but don´t know why it doesnt works.
My Cura Version: 15.02.1

**Comment by adeebshihadeh** [comment]
Can you send me a screenshot of the 'failed to save' message?

**Comment by goblingift** [comment]
Oh yes sure- here is the screenshot of Cura- which is giving me this error, after i clicked your "wifi-symbol":
![image](https://cloud.githubusercontent.com/assets/8299121/9389114/8ca37356-4769-11e5-9363-c681194cce4f.png)

These are my machine settings:
![image](https://cloud.githubusercontent.com/assets/8299121/9389132/ada0a146-4769-11e5-8e93-c58d8c003314.png)

Is the port always 5000 by default? Or do i need a port forward of my router (Don´t think so- if it´s in my home network?)
 I´m having octoprint: 1.2.4.

**Comment by quillford** [comment]
Try changing the port to 80

**Comment by adeebshihadeh** [comment]
That isn't my plugin.... all of the settings would appear in the plugins section. But you should try port 80 anyway. If that doesn't work, file an issue on the repo of the plugin you are using.

**Comment by goblingift** [comment]
Sorry, my fault. I tried now your plugin and it works, thank you :)
But is the only option to upload the sliced gcode, by enabling the option in your plugin "Upload gcode after slice"? So there isn´t any other way, like a button to upload?

**Comment by adeebshihadeh** [comment]
Unfortunately that is the most elegant way I could implement it without forking Cura. Another option would have been to have a pop up ask if you wanted to upload which would have been far more annoying IMO.

**Comment by adeebshihadeh** [comment]
The new Cura (15.06+) will be able to have it done in a much more elegant and natural way but I don't have any immediate plans for rewriting OctoUpload for it.
